In [1]:
# Geo 439: Geophysics 
import numpy as np
import math as m
import pandas as pd
import matplotlib.pyplot as plt

# Defining Constants

In [2]:
m_AU = 1.496e11 #m

# Astro Specific 

Msun = 1.9891e30 #kg #C&O
Lsun = 3.839e26 #W
Tesun = 5777 #K
Rsun = 6.95508e08 #m

Mearth = 5.9736e24 #kg
Req = 6378.1e3 #m #equitorial radius

Mjupiter = 1898.19e24 #kg
ajupiter = 778.6e9 #m

Rmoon = 1738.1e3 #m
Mmoon = 0.07346e24 #kg
amoon = 0.3844e9 #m
Dmoon = 3347 #kg/m3
Rmooncore = 400e3 #m
Dmoonmantle = 3300 #kg/m3

Mpluto = 1.303e22 # kg; radius 
Rpluto = 1188e3 #m and Charon (mass 
Mcharon = 1.586e21 # kg; radius 
Rcharon = 606e3 #m
acharon = 19590e3 #m

# Homework 2

In [3]:
rl = 3.841e8 #m
e = 0.0549

b = (rl**4*(1-e**2))**0.25
a = (rl**4/(1-e**2))**0.25
m.sqrt(a*b)
f'{b:.5e}'

'3.83810e+08'

In [4]:
f'{a*e:.5e}'

f'{a*(1-e):.5e}'

'3.63287e+08'

## p2

In [5]:
Mearth*m_AU/(Msun + Mearth)/Rsun

0.0006459630559121175

In [6]:
Mjupiter*ajupiter / (Msun + Mjupiter)/Rsun

1.067286670558511

In [7]:
Mmoon * amoon /(Mearth + Mmoon) /Req

0.732147697836925

In [8]:
Mcharon*acharon / (Mpluto + Mcharon) /Rpluto

1.789339066637917

## p4

In [9]:
(Rmoon/Rmooncore)**3 *(Dmoon - Dmoonmantle) + Dmoonmantle

7156.045614297296

In [10]:
4/3*m.pi*(Rmoon**3 - Rmooncore**3)*Dmoonmantle + 4/3*m.pi*(Rmooncore**3)*7156.045614297296

7.361538714045452e+22

In [11]:
Mmoon

7.346e+22

# Homework 3

## p3

In [66]:
40+ 43/60

deg = np.array([[40+43/60,-74-1/60],
          [40+25/60,-3-43/60],
          [47+21/60,-122-12/60],
          [-33+52/60,151+13/60],
          [55+45/60,37+35/60],
          [48+52/60,2+20/60],
          [51+30/60,-0-10/60],
          [35+42/60,139+46/60]])

'''
{New York: (λ1 = 40+ 43/60, 74+ 1/60),
Madrid: (λ2 = 40◦ 25’ N, 3+43/60)}
(b) Seattle (λ1 = 47◦ 21’ N, ϕ1 = 122◦ 12’ W)
Sydney (λ2 = 33◦ 52’ S, ϕ2 = 151◦ 13’ E);
(c) Moscow (λ1 = 55◦ 45’ N, ϕ1 = 37◦ 35’ E)
Paris (λ2 = 48◦ 52’ N, ϕ2 = 2◦ 20’ E);
(d) London (λ1 = 51◦ 30’ N, ϕ1 = 0◦ 10’ W)
Tokyo (λ2 = 35◦ 42’ N, ϕ2 = 139◦ 46’ E).
'''

rad = np.radians(deg)
rad

array([[ 0.71063989, -1.29183453],
       [ 0.70540391, -0.06486807],
       [ 0.8264134 , -2.13279235],
       [-0.56083247,  2.63922872],
       [ 0.97302106,  0.65595291],
       [ 0.85288423,  0.04072435],
       [ 0.89884456, -0.00290888],
       [ 0.62308254,  2.43938852]])

In [30]:
from numpy import cos, sin, sqrt

In [72]:
delta = np.zeros(4)


for i in np.arange(0,8,2):
    [l1,p1] = rad[i]
    [l2,p2] = rad[i+1]
    #print(l1,p1)
    #print(l2,p2)
    
    d = np.arccos( cos(l1)*cos(l2)*cos(p2-p1) + sin(l1)*sin(l2) )
    delta[i//2] = d

    print(delta[i//2],'\n')


0.9052997023509719 

1.9358686285683526 

0.38999975187293423 

1.5009384709049003 



In [71]:
delta*180/np.pi

array([ 51.86985214, 110.91710211,  22.34533979,  85.99743969])

In [69]:
delta*6371

array([ 5767.66440368, 12333.41903261,  2484.68841918,  9562.47899814])

## p4

In [88]:
head = np.zeros(4)


for i in np.arange(0,8,2):
    [l1,p1] = rad[i]
    [l2,p2] = rad[i+1]
    #print(l1,p1)
    #print(l2,p2)
    
    d = np.arccos( cos(l1)*cos(l2)*cos(p2-p1) + sin(l1)*sin(l2) )
    print(d)

    [c1, c2] = [np.pi/2 - l1, np.pi/2 - l2]

    head[i//2] = np.arcsin( sin(c2) * sin(p2 - p1) / sin(d))
    print(head[i//2])
    print(head[i//2]*180/np.pi,'\n')
    

0.9052997023509719
1.146277446606748
65.67685984159922 

1.9358686285683526
-1.1312508863151303
-64.81590135629067 

0.38999975187293423
-1.517775686298957
-86.96214107250225 

1.5009384709049003
0.5515391602944593
31.600866121061905 

